### ISSUE TITLE
Experienced issue with Code Display package in concrete5.7.5.3

### ISSUE THREAD

**Issue by volsunghawk** [Mesuva/msv_code_display#1]
Hi, Mesuva.

We installed the Code Display package in our environment running 5.7.5.3 and while it seems to work just fine, we had a very strange error show up. One of our users attempted to edit a page that didn't have a Code Display block at all. She was unable to go into edit mode and see anything on this particular page. I verified that all users outside of Admin users were unable to see anything on that page in edit mode (even the toolbar was blank). When I checked the Logs via the Dashboard, I saw page after page filled with the following error:

Exception Occurred: /var/www/html/tokb/concrete/vendor/symfony/class-loader/Symfony/Component/ClassLoader/MapClassLoader.php:51 Symfony\Component\ClassLoader\MapClassLoader::loadClass(): Failed opening required '/var/www/html/tokb/packages/msv_code_display/controller.php' (include_path='/var/www/html/tokb/concrete/vendor:.:/usr/share/pear:/usr/share/php') (64)

When I went back and uninstalled the package, the user was again able to edit her page successfully.

I've got no idea what could have caused this, and I have no idea why it seemed that installing/uninstalling this package would affect a page that didn't use it at all.

Anyhow, below is my environment info (without the Code Display block):
# concrete5 Version

Core Version - 5.7.5.3
Version Installed - 5.7.5.3
Database Version - 20150731000000
# concrete5 Packages

Accordion Menu (3.0), Block Designer (1.2.8), C5DK TwentyTwenty Image (1.0.1), Call to Action (1.0.0), Call to Action Pro (1.0.0), Easy Rate (1.0.0), Easy Weather (0.9.1), Editor Comment (7.0.1), ExchangeCore LDAP Authentication (1.2.1), Honest Websites Back To Top (0.9.4), HTML+PHP Code Block (1.0.1), Icons for Redactor (0.9.1), List Designer (0.9.5), List files from set (1.0.10), Login/Logout Link (1.0), Login Page Background (0.9), Magic Tabs (7.0.1), Page Activity (0.9.3), Page List+ (1.3.1), Page Selector Attribute (2.0), PDF Viewer (1.0.1), Pending Pages (0.9.2), ProEvents (2.7.3.1), Quick Tabs (1.0), Raptorize (2.0), Spacer (0.9.2), Stack Popover (1.2.2), Supermint Theme (3.3.1.3), Tokens (1.0.0), Up Down Vote Lister (2.0.9).
# concrete5 Overrides

languages/da_DK/LC_MESSAGES/messages.mo, languages/da_DK/LC_MESSAGES, languages/da_DK, languages/de_DE/LC_MESSAGES/messages.mo, languages/de_DE/LC_MESSAGES, languages/de_DE, languages/el_GR/LC_MESSAGES/messages.mo, languages/el_GR/LC_MESSAGES, languages/el_GR, languages/fi_FI/LC_MESSAGES/messages.mo, languages/fi_FI/LC_MESSAGES, languages/fi_FI, languages/fr_FR/LC_MESSAGES/messages.mo, languages/fr_FR/LC_MESSAGES, languages/fr_FR, languages/it_IT/LC_MESSAGES/messages.mo, languages/it_IT/LC_MESSAGES, languages/it_IT, languages/ja_JP/LC_MESSAGES/messages.mo, languages/ja_JP/LC_MESSAGES, languages/ja_JP, languages/nb_NO/LC_MESSAGES/messages.mo, languages/nb_NO/LC_MESSAGES, languages/nb_NO, languages/nl_NL/LC_MESSAGES/messages.mo, languages/nl_NL/LC_MESSAGES, languages/nl_NL, languages/pl_PL/LC_MESSAGES/messages.mo, languages/pl_PL/LC_MESSAGES, languages/pl_PL, languages/pt_BR/LC_MESSAGES/messages.mo, languages/pt_BR/LC_MESSAGES, languages/pt_BR, languages/ru_RU/LC_MESSAGES/messages.mo, languages/ru_RU/LC_MESSAGES, languages/ru_RU, languages/sv_SE/LC_MESSAGES/messages.mo, languages/sv_SE/LC_MESSAGES, languages/sv_SE, languages/tr_TR/LC_MESSAGES/messages.mo, languages/tr_TR/LC_MESSAGES, languages/tr_TR, tools/pages/preview_version.php, tools/pages, languages/da_DK/LC_MESSAGES/messages.mo, languages/da_DK/LC_MESSAGES, languages/da_DK, languages/de_DE/LC_MESSAGES/messages.mo, languages/de_DE/LC_MESSAGES, languages/de_DE, languages/el_GR/LC_MESSAGES/messages.mo, languages/el_GR/LC_MESSAGES, languages/el_GR, languages/fi_FI/LC_MESSAGES/messages.mo, languages/fi_FI/LC_MESSAGES, languages/fi_FI, languages/fr_FR/LC_MESSAGES/messages.mo, languages/fr_FR/LC_MESSAGES, languages/fr_FR, languages/it_IT/LC_MESSAGES/messages.mo, languages/it_IT/LC_MESSAGES, languages/it_IT, languages/ja_JP/LC_MESSAGES/messages.mo, languages/ja_JP/LC_MESSAGES, languages/ja_JP, languages/nb_NO/LC_MESSAGES/messages.mo, languages/nb_NO/LC_MESSAGES, languages/nb_NO, languages/nl_NL/LC_MESSAGES/messages.mo, languages/nl_NL/LC_MESSAGES, languages/nl_NL, languages/pl_PL/LC_MESSAGES/messages.mo, languages/pl_PL/LC_MESSAGES, languages/pl_PL, languages/pt_BR/LC_MESSAGES/messages.mo, languages/pt_BR/LC_MESSAGES, languages/pt_BR, languages/ru_RU/LC_MESSAGES/messages.mo, languages/ru_RU/LC_MESSAGES, languages/ru_RU, languages/sv_SE/LC_MESSAGES/messages.mo, languages/sv_SE/LC_MESSAGES, languages/sv_SE, languages/tr_TR/LC_MESSAGES/messages.mo, languages/tr_TR/LC_MESSAGES, languages/tr_TR, tools/pages/preview_version.php, tools/pages
# concrete5 Cache Settings

Block Cache - Off
Overrides Cache - On
Full Page Caching - Off
Full Page Cache Lifetime - Every 6 hours (default setting).
# Server Software

Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.1e-fips PHP/5.4.16
# Server API

apache2handler
# PHP Version

5.4.16
# PHP Extensions

apache2handler, bcmath, bz2, calendar, Core, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, json, ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcre, PDO, pdo_mysql, pdo_sqlite, Phar, posix, Reflection, session, shmop, SimpleXML, sockets, SPL, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zip, zlib.
# PHP Settings

max_execution_time - 180
log_errors_max_len - 1024
max_file_uploads - 20
max_input_nesting_level - 64
max_input_time - 60
max_input_vars - 1000
memory_limit - 512M
post_max_size - 100M
sql.safe_mode - Off
upload_max_filesize - 100M
ldap.max_links - Unlimited
mysql.max_links - Unlimited
mysql.max_persistent - Unlimited
mysqli.max_links - Unlimited
mysqli.max_persistent - Unlimited
pcre.backtrack_limit - 1000000
pcre.recursion_limit - 100000
session.cache_limiter - <i>no value</i>
session.gc_maxlifetime - 1440

**Comment by Mesuva** [comment]
That's a strange one.

From the error message the only thing I can think of is that the controller.php file in the package ended up with the wrong permissions or was deleted at some stage. 

It's very strange though that it was happening on one page and not for all. If you delete an active package's controller.php file a whole site will break until the package is remove via the database.
