### ISSUE TITLE
Ace Theme JS not available errors on selecting theme

### ISSUE THREAD

**Issue by sharadkap** [Mesuva/msv_code_display#2]
On using the block when a theme is selected, the block throws an error on javascripts not found. 
See attachments. Its looking for the js at the root of the website where it should look for those in the concrete/js/ace folder. 
Do you have a fix for this?

![screen shot 2017-11-05 at 1 31 16 pm](https://user-images.githubusercontent.com/5682531/32411418-2373ba66-c22e-11e7-9bff-c4896e2989d8.png)
![screen shot 2017-11-05 at 1 31 36 pm](https://user-images.githubusercontent.com/5682531/32411419-23dbb698-c22e-11e7-857d-424eeb621da4.png)
![screen shot 2017-11-05 at 1 31 49 pm](https://user-images.githubusercontent.com/5682531/32411420-25cdc5b8-c22e-11e7-9251-10a57b683379.png)
![screen shot 2017-11-05 at 1 32 07 pm](https://user-images.githubusercontent.com/5682531/32411421-264c1972-c22e-11e7-89cc-f04cd16ae766.png)

**Comment by sharadkap** [comment]
False alarm - it was just caching issue.

**Comment by Mesuva** [comment]
Thanks for investigating further and following up - good luck!

**Comment by sharadkap** [comment]
Thanks @Mesuva!
