### ISSUE TITLE
Problems when CSS and JavaScript Cache is enabled

### ISSUE THREAD

**Issue by a3020** [Mesuva/msv_code_display#3]
@Mesuva thanks a lot for open sourcing this package. 🎈 

I found a minor bug in 8.4.2, I think. When **CSS and JavaScript Cache** is enabled (/index.php/dashboard/system/optimization/cache/), I get errors in the console, and code highlighting doesn't seem to work. It doesn't seem to load 'theme-chrome.js' and 'mode-php.js'. Is this a known issue?

**Comment by Mesuva** [comment]
It's not an issue I've seen, but I also don't use this add-on very often myself!

It's including the ace editor asset in a pretty normal way, so I'd say it's some sort of issue with the way that ace pulls in the other resources it needs.

**Comment by a3020** [comment]
OK, yeah that sounds likely. It's not a huge deal for me, so I'll close this issue. But now you know what's going on when someone says code highlighting isn't working when a user is not logged in. ;)
