### ISSUE TITLE
Code highlight not working

### ISSUE THREAD

**Issue by walec51** [Mesuva/msv_code_display#4]
Had to add:

```
ace.config.set("basePath", "/concrete/js/ace/");
```
to make it work.

Without it ACE was trying to load js files from the current path (for ex. /sites-page/theme-chrome.js)

**Comment by Mesuva** [comment]
Thanks for this - to confirm, this is to handle cases where you are running concrete5 out of a folder on a server, and not at the document root?

**Comment by Mesuva** [comment]
Could you provide a bit more detail as to where you added this extra line?
And did you also have to make any edits to edit.php for when you are _editing_ the block?

**Comment by ebmudremyc** [comment]
I experience this same issue, but only when CSS/JS caching is on. 
I added the line 
`ace.config.set("basePath", '<?php echo ASSETS_URL_JAVASCRIPT?>/ace');`
on line 17 of blocks/msv_code_display/view.php

**Comment by Mesuva** [comment]
Thank you for this, and sorry for the delay - I've pushed up a fix
