### ISSUE TITLE
Compatibility with concreteCMS 9 and PHP 8.1 

### ISSUE THREAD

**Issue by webpresso-ch** [Mesuva/msv_code_display#5]
We still have this package with one customer. There we have just updated to concreteCMS9 and PHP 8.1. 
We noticed that the version of concreteCMS Addons Marketplace is marked version 9 ready but unfortunately still has errors. 
Therefore we created a fork and adapted the package to concreteCMS 9 and PHP 8.1. 

Gladly take over our adjustments for the Marketplace. 
Here you can find our customizations 
https://github.com/Webpresso-AG/msv_code_display/commit/3f97f19156e6e85124f16714d5637bc422bf77f9 

Thanks a lot!

**Comment by Mesuva** [comment]
Thanks for this - I think I must have updated the add-on quite early for V9, but that was before PHP8 was a major consideration.

Any chance you can do a pull request with your changes?
I'll update the marketplace copy as soon as I can.

**Comment by webpresso-ch** [comment]
I'm happy to do it!
Pull request created. Just take over... ;-)

https://github.com/Mesuva/msv_code_display/pull/6

**Comment by webpresso-ch** [comment]
Solved with https://github.com/Mesuva/msv_code_display/pull/6
